services:
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5001/api
      - VITE_MEDIA_URL=https://res.cloudinary.com/dmtpqwfyu/image/upload/v1734531804/

  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgresql://postgres:postgres@db:5432/vending_machine?schema=public
    ports:
      - "5001:5001"
    volumes:
      - /app/node_modules
      - /app/.pnpm-store
    environment:
      - NODE_ENV=development
      - PORT=5001
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/vending_machine?schema=public
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vending_machine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d vending_machine"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 30s

volumes:
  postgres_data:
