services:
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./be:/app
      - /app/node_modules
      - /app/.pnpm-store
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/vending_machine?schema=public
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vending_machine
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
